I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 210, in script
    pos (960, 460) "thank u for playing"
Exception: Sayer 'pos (960, 460)' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 210, in script
    pos (960, 460) "thank u for playing"
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'pos (960, 460)' is not defined.

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
Joe And Mysterious Treasure 1.0
Sun Apr 16 17:58:36 2023
